from __future__ import annotations

import base64
import html
from pathlib import Path
from typing import Any, Iterable

import streamlit as st


EDL_NAVY = "#071C3A"
EDL_NAVY_2 = "#0B2D57"
EDL_NAVY_3 = "#123D70"
EDL_GOLD = "#C78B12"
EDL_GOLD_LIGHT = "#E5B13C"
EDL_RED = "#D92D20"
EDL_GREEN = "#178A52"
EDL_BLUE = "#2563EB"
EDL_PURPLE = "#6941C6"
EDL_TEAL = "#087E8B"
EDL_BG = "#F4F7FB"
EDL_TEXT = "#16213A"
EDL_MUTED = "#667085"
EDL_BORDER = "#DCE3EC"


def _asset_path(filename: str) -> Path:
    return Path(__file__).resolve().parent / "assets" / filename


def _asset_data_uri(filename: str) -> str:
    path = _asset_path(filename)
    if not path.exists():
        return ""
    mime = "image/png" if path.suffix.lower() == ".png" else "image/jpeg"
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def _logo_data_uri() -> str:
    return _asset_data_uri("edl_logo.png")


def _audit_image_data_uri() -> str:
    return _asset_data_uri("internal_audit_visual.png")


def _render_html(fragment: str) -> None:
    """Render controlled local HTML in the main Streamlit document.

    ``st.markdown`` is used deliberately because global CSS and layout HTML need
    to share the same document as Streamlit widgets. The fragments generated by
    this module are compact and contain only trusted local content.
    """
    st.markdown(fragment, unsafe_allow_html=True)


def apply_iars_theme() -> None:
    """Apply the EDL Internal Audit professional visual system."""
    css = f"""
<style>
:root {{
  --edl-navy:{EDL_NAVY}; --edl-navy-2:{EDL_NAVY_2}; --edl-navy-3:{EDL_NAVY_3};
  --edl-gold:{EDL_GOLD}; --edl-gold-light:{EDL_GOLD_LIGHT}; --edl-red:{EDL_RED};
  --edl-green:{EDL_GREEN}; --edl-blue:{EDL_BLUE}; --edl-purple:{EDL_PURPLE};
  --edl-teal:{EDL_TEAL}; --edl-bg:{EDL_BG}; --edl-text:{EDL_TEXT};
  --edl-muted:{EDL_MUTED}; --edl-border:{EDL_BORDER};
}}
html,body,[class*="css"],.stApp {{
  font-family:Inter,"Segoe UI",Roboto,Arial,sans-serif;
}}
.stApp {{
  background:
    radial-gradient(circle at 90% 0%,rgba(199,139,18,.07),transparent 24rem),
    linear-gradient(180deg,#F9FBFE 0%,var(--edl-bg) 100%);
  color:var(--edl-text);
}}
.block-container {{max-width:1500px;padding-top:1.25rem;padding-bottom:3rem;}}
header[data-testid="stHeader"] {{background:rgba(249,251,254,.86);backdrop-filter:blur(14px);}}
#MainMenu {{visibility:hidden;}}
footer {{visibility:hidden;}}

section[data-testid="stSidebar"] {{
  background:linear-gradient(180deg,#06182F 0%,#08254A 55%,#061A35 100%);
  border-right:1px solid rgba(255,255,255,.08);
}}
section[data-testid="stSidebar"] > div {{padding-top:.55rem;}}
section[data-testid="stSidebar"] * {{color:#F8FAFC;}}
section[data-testid="stSidebar"] [data-testid="stCaptionContainer"],
section[data-testid="stSidebar"] .stCaption {{color:rgba(255,255,255,.62)!important;}}
section[data-testid="stSidebar"] hr {{border-color:rgba(255,255,255,.11);}}
section[data-testid="stSidebar"] [data-testid="stRadio"] label {{
  border-radius:10px;padding:.38rem .55rem;margin:.08rem 0;transition:.15s ease;
}}
section[data-testid="stSidebar"] [data-testid="stRadio"] label:hover {{
  background:rgba(255,255,255,.08);
}}
section[data-testid="stSidebar"] [data-testid="stRadio"] label:has(input:checked) {{
  background:linear-gradient(135deg,#B97808,#D89F22);
  box-shadow:0 7px 18px rgba(199,139,18,.25);
}}
section[data-testid="stSidebar"] [data-testid="stRadio"] label:has(input:checked) p {{color:#FFFFFF!important;font-weight:760;}}
section[data-testid="stSidebar"] .stButton>button {{
  border-radius:10px;border-color:rgba(255,255,255,.18);background:rgba(255,255,255,.07);color:white;
}}
section[data-testid="stSidebar"] .stButton>button:hover {{
  background:rgba(199,139,18,.22);border-color:rgba(229,177,60,.58);
}}

.edl-brand-stripe {{height:4px;border-radius:99px;background:linear-gradient(90deg,#1665D8 0 24%,#169B45 24% 49%,#E8B629 49% 74%,#E3282C 74% 100%);}}
.edl-sidebar-brand {{text-align:center;padding:.35rem .2rem .8rem;}}
.edl-sidebar-brand img {{width:132px;max-width:78%;object-fit:contain;filter:drop-shadow(0 10px 22px rgba(0,0,0,.25));}}
.edl-sidebar-brand h3 {{margin:.55rem 0 .05rem;font-size:1rem;letter-spacing:.03em;color:#FFF;}}
.edl-sidebar-brand p {{margin:0;color:rgba(255,255,255,.64)!important;font-size:.73rem;letter-spacing:.035em;text-transform:uppercase;}}

.edl-app-header {{
  display:flex;align-items:center;gap:1rem;padding:.88rem 1.05rem;background:rgba(255,255,255,.96);
  border:1px solid var(--edl-border);border-radius:16px;box-shadow:0 8px 26px rgba(7,28,58,.06);margin-bottom:.9rem;
}}
.edl-app-logo {{width:70px;height:70px;object-fit:contain;flex:0 0 auto;}}
.edl-app-kicker {{color:var(--edl-gold);font-size:.72rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase;}}
.edl-app-title {{margin:.18rem 0 0;color:var(--edl-navy);font-size:clamp(1.45rem,2.6vw,2.15rem);line-height:1.08;font-weight:820;letter-spacing:-.03em;}}
.edl-app-subtitle {{color:var(--edl-muted);margin-top:.28rem;font-size:.88rem;}}
.edl-user-chip {{margin-left:auto;background:#F8FAFC;border:1px solid var(--edl-border);border-radius:12px;padding:.55rem .75rem;min-width:170px;text-align:right;}}
.edl-user-chip strong {{color:var(--edl-navy);font-size:.9rem;}}
.edl-user-chip span {{color:var(--edl-muted);font-size:.74rem;}}

.edl-section-head {{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;margin:.55rem 0 .85rem;}}
.edl-section-head h2 {{margin:0;color:var(--edl-navy);font-size:1.45rem;letter-spacing:-.02em;}}
.edl-section-head p {{margin:.22rem 0 0;color:var(--edl-muted);font-size:.9rem;}}
.edl-section-badge {{white-space:nowrap;border:1px solid rgba(199,139,18,.28);background:rgba(199,139,18,.09);color:#80590B;border-radius:999px;padding:.38rem .62rem;font-size:.72rem;font-weight:760;}}

.edl-metric-grid {{display:grid;grid-template-columns:repeat(auto-fit,minmax(175px,1fr));gap:.72rem;margin:.15rem 0 1rem;}}
.edl-metric-card {{position:relative;overflow:hidden;background:#FFF;border:1px solid var(--edl-border);border-radius:14px;padding:.9rem 1rem;box-shadow:0 6px 18px rgba(7,28,58,.045);}}
.edl-metric-card:before {{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--accent,var(--edl-gold));}}
.edl-metric-icon {{position:absolute;right:.8rem;top:.7rem;font-size:1.25rem;opacity:.86;}}
.edl-metric-label {{color:var(--edl-muted);font-size:.7rem;font-weight:760;text-transform:uppercase;letter-spacing:.045em;}}
.edl-metric-value {{color:var(--edl-navy);font-size:1.55rem;font-weight:830;line-height:1.15;margin:.28rem 0 .16rem;}}
.edl-metric-note {{color:var(--edl-muted);font-size:.73rem;}}

.edl-feature-grid {{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:.75rem;margin:.15rem 0 1rem;}}
.edl-feature-card {{min-height:128px;background:linear-gradient(145deg,#FFF,#FBFCFE);border:1px solid var(--edl-border);border-radius:14px;padding:.9rem;box-shadow:0 6px 18px rgba(7,28,58,.04);}}
.edl-feature-icon {{font-size:1.35rem;margin-bottom:.45rem;}}
.edl-feature-card h4 {{margin:0 0 .25rem;color:var(--edl-navy);font-size:.96rem;}}
.edl-feature-card p {{margin:0;color:var(--edl-muted);font-size:.79rem;line-height:1.48;}}

.edl-dashboard-hero {{
  position:relative;isolation:isolate;overflow:hidden;min-height:270px;border-radius:20px;
  border:1px solid var(--edl-border);background:linear-gradient(135deg,#FFFFFF 0%,#F8FAFD 100%);
  box-shadow:0 14px 34px rgba(7,28,58,.075);padding:2.15rem 2.25rem;margin:.3rem 0 1rem;
}}
.edl-dashboard-hero:before {{content:"";position:absolute;inset:0;background:linear-gradient(90deg,#FFF 0%,rgba(255,255,255,.98) 43%,rgba(255,255,255,.70) 62%,rgba(255,255,255,.12) 100%);z-index:-1;}}
.edl-dashboard-visual {{position:absolute;right:-1%;top:-8%;width:min(52%,620px);height:116%;object-fit:cover;object-position:center right;z-index:-2;filter:saturate(.92) contrast(1.03);}}
.edl-dashboard-hero h1 {{max-width:590px;color:var(--edl-navy);font-size:clamp(2rem,4vw,3.1rem);line-height:1.04;letter-spacing:-.045em;margin:0 0 .65rem;font-weight:850;}}
.edl-dashboard-hero h1 em {{color:var(--edl-gold);font-style:normal;}}
.edl-dashboard-hero p {{max-width:590px;color:#526077;font-size:.98rem;line-height:1.58;margin:0;}}
.edl-hero-tag {{display:inline-flex;align-items:center;gap:.38rem;background:rgba(7,28,58,.06);color:var(--edl-navy);border:1px solid rgba(7,28,58,.1);border-radius:999px;padding:.36rem .62rem;font-size:.72rem;font-weight:750;margin-bottom:.75rem;}}

.edl-login-wrap {{min-height:calc(100vh - 3rem);display:flex;align-items:center;}}
.edl-login-hero {{
  position:relative;isolation:isolate;overflow:hidden;min-height:650px;border-radius:24px;padding:2.35rem;
  color:white;background:linear-gradient(145deg,#061831 0%,#08264D 56%,#071C3A 100%);
  border:1px solid rgba(255,255,255,.09);box-shadow:0 24px 64px rgba(7,28,58,.22);
}}
.edl-login-hero:before {{content:"";position:absolute;inset:0;background:radial-gradient(circle at 18% 8%,rgba(37,99,235,.18),transparent 28rem),linear-gradient(90deg,rgba(5,22,47,.98) 0%,rgba(5,25,52,.94) 49%,rgba(5,24,49,.38) 75%,rgba(5,24,49,.08) 100%);z-index:-1;}}
.edl-login-visual {{position:absolute;right:-3%;bottom:-1%;width:69%;height:94%;object-fit:cover;object-position:center right;z-index:-2;opacity:.94;filter:saturate(.88) contrast(1.05);}}
.edl-login-content {{position:relative;z-index:2;max-width:57%;}}
.edl-login-hero .edl-login-logo {{width:180px;max-width:72%;height:auto;object-fit:contain;margin-bottom:1.35rem;filter:drop-shadow(0 10px 24px rgba(0,0,0,.30));}}
.edl-login-hero .eyebrow {{color:#F0C65A;font-size:.73rem;font-weight:820;letter-spacing:.14em;text-transform:uppercase;}}
.edl-login-hero h1 {{color:white;font-size:clamp(2.15rem,4vw,3.35rem);letter-spacing:-.045em;line-height:1.03;margin:.5rem 0 .8rem;font-weight:850;}}
.edl-login-hero h1 em {{color:#F0C65A;font-style:normal;}}
.edl-login-hero p {{color:rgba(255,255,255,.79);max-width:500px;font-size:.96rem;line-height:1.65;}}
.edl-login-points {{display:grid;grid-template-columns:1fr;gap:.55rem;margin-top:1.25rem;max-width:385px;}}
.edl-login-point {{display:flex;align-items:center;gap:.62rem;background:rgba(255,255,255,.075);border:1px solid rgba(255,255,255,.14);border-radius:12px;padding:.72rem .82rem;color:white;font-size:.8rem;backdrop-filter:blur(8px);}}
.edl-login-point span {{display:inline-flex;width:1.55rem;height:1.55rem;align-items:center;justify-content:center;border-radius:8px;background:rgba(240,198,90,.13);}}
.edl-login-foot {{position:absolute;left:2.35rem;right:2.35rem;bottom:1.35rem;color:rgba(255,255,255,.61);font-size:.71rem;border-top:1px solid rgba(255,255,255,.13);padding-top:.8rem;z-index:2;}}

.st-key-iars_auth_card {{background:#FFFFFF;border:1px solid var(--edl-border);border-radius:20px;padding:1.1rem 1.15rem 1.25rem;box-shadow:0 18px 48px rgba(7,28,58,.10);}}
.st-key-iars_auth_card [data-testid="stForm"] {{box-shadow:none;background:#FFFFFF;border:1px solid #E3E8EF!important;border-radius:14px!important;}}
.st-key-iars_auth_card .stTabs [data-baseweb="tab-list"] {{box-shadow:none;margin-bottom:.45rem;}}
.st-key-iars_auth_card .stTextInput input {{background:#F8FAFC;border-color:#D8E0EA;min-height:46px;}}
.st-key-iars_auth_card .stTextInput input:focus {{border-color:var(--edl-gold);box-shadow:0 0 0 3px rgba(199,139,18,.12);}}

.edl-user-card {{background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.12);border-radius:13px;padding:.75rem .8rem;margin:.35rem 0 .6rem;}}
.edl-user-card strong {{display:block;color:#FFF;font-size:.9rem;}}
.edl-user-card span {{color:rgba(255,255,255,.64);font-size:.73rem;}}
.edl-status-card {{border-radius:12px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.07);padding:.68rem .76rem;margin:.3rem 0 .55rem;color:#FFF;}}
.edl-status-card strong {{color:#FFF;display:block;margin-bottom:.12rem;font-size:.82rem;}}
.edl-status-card span {{color:rgba(255,255,255,.68);font-size:.72rem;}}
.edl-status-dot {{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:.38rem;background:var(--dot,var(--edl-green));box-shadow:0 0 0 3px rgba(23,138,82,.16);}}

.edl-library-note {{display:flex;gap:.7rem;align-items:flex-start;padding:.85rem .95rem;border:1px solid #CFE0F5;background:#F4F8FE;border-radius:12px;margin:.25rem 0 .8rem;}}
.edl-library-note strong {{color:var(--edl-navy);}}
.edl-library-note span {{color:var(--edl-muted);font-size:.8rem;}}

.stButton>button,.stDownloadButton>button,button[kind="primary"] {{border-radius:9px;font-weight:730;transition:.12s ease;}}
.stButton>button:hover,.stDownloadButton>button:hover {{transform:translateY(-1px);box-shadow:0 7px 16px rgba(7,28,58,.10);}}
button[kind="primary"] {{background:linear-gradient(135deg,#B77908,#DDAA2E)!important;color:white!important;border:1px solid #A96E06!important;}}
[data-testid="stFileUploaderDropzone"] {{border:1.5px dashed rgba(37,99,235,.38);background:linear-gradient(145deg,rgba(37,99,235,.025),rgba(199,139,18,.035));border-radius:14px;padding:1rem;}}
[data-testid="stMetric"] {{background:#FFF;border:1px solid var(--edl-border);border-radius:13px;padding:.78rem .9rem;box-shadow:0 5px 16px rgba(7,28,58,.04);}}
[data-testid="stDataFrame"],[data-testid="stDataEditor"] {{border:1px solid var(--edl-border);border-radius:12px;overflow:hidden;box-shadow:0 5px 18px rgba(7,28,58,.04);}}
[data-testid="stAlert"] {{border-radius:11px;border-width:1px;}}
div[data-testid="stForm"],div[data-testid="stVerticalBlockBorderWrapper"] {{border-color:var(--edl-border)!important;border-radius:15px!important;box-shadow:0 7px 22px rgba(7,28,58,.04);background:rgba(255,255,255,.97);}}
.stTabs [data-baseweb="tab-list"] {{gap:.28rem;background:#FFF;border:1px solid var(--edl-border);padding:.28rem;border-radius:11px;box-shadow:0 4px 14px rgba(7,28,58,.035);}}
.stTabs [data-baseweb="tab"] {{border-radius:8px;padding:.48rem .75rem;color:var(--edl-muted);font-weight:700;}}
.stTabs [aria-selected="true"] {{background:rgba(199,139,18,.11)!important;color:#78520A!important;}}
.stTabs [data-baseweb="tab-highlight"] {{background-color:var(--edl-gold)!important;}}

@media(max-width:1000px) {{.edl-user-chip{{display:none}}.edl-login-hero{{min-height:600px}}.edl-login-content{{max-width:64%}}.edl-login-visual{{width:72%;opacity:.78}}}}
@media(max-width:700px) {{
  .block-container{{padding-left:.9rem;padding-right:.9rem}}
  .edl-app-header{{align-items:flex-start}}.edl-app-logo{{width:56px;height:56px}}
  .edl-login-points{{grid-template-columns:1fr}}.edl-login-hero{{min-height:560px;padding:1.35rem}}.edl-login-content{{max-width:100%}}.edl-login-visual{{width:100%;opacity:.24}}
  .edl-login-foot{{left:1.35rem;right:1.35rem}}.edl-dashboard-hero{{padding:1.35rem}}.edl-dashboard-visual{{opacity:.20;width:100%}}
}}
</style>
"""
    _render_html(css)


def render_brand_stripe() -> None:
    _render_html('<div class="edl-brand-stripe"></div>')


def render_sidebar_brand() -> None:
    logo = _logo_data_uri()
    image = f'<img src="{logo}" alt="EDL GROUP OF COMPANIES logo">' if logo else ""
    _render_html(
        '<div class="edl-sidebar-brand">'
        f'{image}<h3>Internal Audit</h3><p>EDL GROUP OF COMPANIES</p>'
        '</div>'
    )


def render_app_header(user: dict[str, Any], *, version: str) -> None:
    logo = _logo_data_uri()
    image = f'<img class="edl-app-logo" src="{logo}" alt="EDL GROUP OF COMPANIES logo">' if logo else ""
    name = html.escape(str(user.get("full_name") or user.get("username") or "IARS User"))
    role = "Administrator" if str(user.get("role", "")).lower() == "admin" else "Auditor"
    _render_html(
        '<div class="edl-brand-stripe"></div>'
        '<div class="edl-app-header">'
        f'{image}<div><div class="edl-app-kicker">EDL GROUP OF COMPANIES</div>'
        '<h1 class="edl-app-title">Internal Audit Report System</h1>'
        f'<div class="edl-app-subtitle">Secure extraction, PDF tagging, shared archives and controlled records · v{html.escape(version)}</div></div>'
        f'<div class="edl-user-chip"><strong>{name}</strong><br><span>{role}</span></div></div>'
    )


def render_login_hero() -> None:
    logo = _logo_data_uri()
    audit_image = _audit_image_data_uri()
    logo_html = (
        f'<img class="edl-login-logo" src="{logo}" alt="EDL GROUP OF COMPANIES logo">'
        if logo else ""
    )
    visual_html = (
        f'<img class="edl-login-visual" src="{audit_image}" alt="Internal audit reports and compliance workpapers">'
        if audit_image else ""
    )
    _render_html(
        '<div class="edl-login-hero">'
        f'{visual_html}<div class="edl-login-content">{logo_html}'
        '<div class="eyebrow">EDL GROUP OF COMPANIES</div>'
        '<h1>Secure Internal Audit <em>Workspace.</em></h1>'
        '<p>Access the Internal Audit Report System for secure report extraction, PDF tagging, shared archive access, reusable templates, policies and controlled audit records.</p>'
        '<div class="edl-login-points">'
        '<div class="edl-login-point"><span>🛡️</span>Admin-approved access</div>'
        '<div class="edl-login-point"><span>📄</span>Smart report extraction</div>'
        '<div class="edl-login-point"><span>🗂️</span>Shared document libraries</div>'
        '<div class="edl-login-point"><span>✅</span>Controlled audit records</div>'
        '</div></div><div class="edl-login-foot">Secure · Confidential · EDL GROUP OF COMPANIES Internal Audit</div></div>'
    )


def render_dashboard_hero() -> None:
    audit_image = _audit_image_data_uri()
    visual_html = (
        f'<img class="edl-dashboard-visual" src="{audit_image}" alt="Internal audit reports and workpapers">'
        if audit_image else ""
    )
    _render_html(
        '<div class="edl-dashboard-hero">'
        f'{visual_html}<div class="edl-hero-tag">🛡️ Internal Audit Digital Workspace</div>'
        '<h1>Delivering Integrity.<br>Driving <em>Assurance.</em></h1>'
        '<p>Empowering the Internal Audit team with secure tools, accurate data, reusable resources and actionable records for confident decision-making.</p>'
        '</div>'
    )


def render_section_header(title: str, subtitle: str = "", badge: str = "") -> None:
    badge_html = f'<div class="edl-section-badge">{html.escape(badge)}</div>' if badge else ""
    _render_html(
        '<div class="edl-section-head"><div>'
        f'<h2>{html.escape(title)}</h2><p>{html.escape(subtitle)}</p></div>{badge_html}</div>'
    )


def render_metric_cards(cards: Iterable[dict[str, Any]]) -> None:
    accents = [EDL_GOLD, EDL_BLUE, EDL_GREEN, EDL_PURPLE, EDL_TEAL, EDL_RED]
    chunks: list[str] = []
    for index, card in enumerate(cards):
        label = html.escape(str(card.get("label", "")))
        value = html.escape(str(card.get("value", "")))
        note = html.escape(str(card.get("note", "")))
        icon = html.escape(str(card.get("icon", "")))
        accent = html.escape(str(card.get("accent") or accents[index % len(accents)]))
        chunks.append(
            f'<div class="edl-metric-card" style="--accent:{accent}">'
            f'<div class="edl-metric-icon">{icon}</div><div class="edl-metric-label">{label}</div>'
            f'<div class="edl-metric-value">{value}</div><div class="edl-metric-note">{note}</div></div>'
        )
    _render_html(f'<div class="edl-metric-grid">{"".join(chunks)}</div>')


def render_feature_cards(cards: Iterable[dict[str, Any]]) -> None:
    chunks: list[str] = []
    for card in cards:
        icon = html.escape(str(card.get("icon", "")))
        title = html.escape(str(card.get("title", "")))
        text = html.escape(str(card.get("text", "")))
        chunks.append(
            f'<div class="edl-feature-card"><div class="edl-feature-icon">{icon}</div>'
            f'<h4>{title}</h4><p>{text}</p></div>'
        )
    _render_html(f'<div class="edl-feature-grid">{"".join(chunks)}</div>')


def render_sidebar_status(title: str, detail: str, *, ok: bool = True) -> None:
    dot = EDL_GREEN if ok else EDL_RED
    _render_html(
        '<div class="edl-status-card">'
        f'<strong><span class="edl-status-dot" style="--dot:{dot}"></span>{html.escape(title)}</strong>'
        f'<span>{html.escape(detail)}</span></div>'
    )


def render_sidebar_user(user: dict[str, Any]) -> None:
    name = html.escape(str(user.get("full_name") or user.get("username") or "IARS User"))
    username = html.escape(str(user.get("username") or ""))
    role = "Administrator" if str(user.get("role", "")).lower() == "admin" else "Auditor"
    _render_html(
        '<div class="edl-user-card">'
        f'<strong>{name}</strong><span>@{username} · {role}</span></div>'
    )


def render_library_note(title: str, detail: str, icon: str = "ℹ️") -> None:
    _render_html(
        '<div class="edl-library-note">'
        f'<div>{html.escape(icon)}</div><div><strong>{html.escape(title)}</strong><br><span>{html.escape(detail)}</span></div></div>'
    )
